export const apiKey = 'YOUR API KEY';

/* TO GET AN API KEY, GO TO https://www.exchangerate-api.com/ ON YOUR BROWSER THEN, CLICK 'GET FREE KEY' BUTTON AND FOLLOW THE INSTRUCTIONS.
   AFTER, YOU CAN PASTE YOUR API KEY INTO SINGLE QUOTES. */